import { externalLinks, marketLinks } from './links';
import { siteUrl } from './site';

export const en = {
    code: 'en',
    switchLabel: '中',
    brandMark: 'ZenMind',
    seo: {
      title: 'ZenMind | Desktop-first AI Agent Platform',
      description:
        'ZenMind is a Desktop-first AI agent platform for local services, web and mobile workflows, Chinese model ecosystems, and local sandboxes.',
      url: `${siteUrl}/en`,
    },
    nav: {
      home: 'Home',
      download: 'Download',
      documents: 'Documents',
      news: 'News',
      market: 'Market',
      login: 'Login',
      adminLogin: 'Admin login',
      profile: 'Profile',
      admin: 'Admin',
      authFailure: 'Sign-in failure',
      github: 'GitHub',
    },
    theme: {
      label: 'Theme',
      auto: 'Auto',
      light: 'Light',
      dark: 'Dark',
    },
    shared: {
      copyLabel: 'Copy',
      copiedLabel: 'Copied',
      openGithub: 'GitHub',
      readDocs: 'Read docs',
      deployDocs: 'Deploy entry',
      downloadDesktop: 'Download desktop',
      openProfile: 'Profile',
      logout: 'Log out',
      currentAccount: 'Current account',
      notSignedIn: 'Not signed in',
      noPermission: 'No permission',
      usagePreparing: 'Usage data is being prepared',
      statusReady: 'Available',
      statusSoon: 'Planned',
      statusPreview: 'Preview',
      externalLabel: 'Open external link',
      downloadFallback: 'Read docs',
      downloadTotalPrefix: '',
      downloadTotalSuffix: ' downloads',
    },
    home: {
      eyebrow: 'Desktop-first AI Agent Platform',
      headline: 'Let AI agents keep working on your desktop',
      heroIntro:
        'ZenMind organizes the desktop app, local services, model connections, and sandbox environments into a controllable workspace where long-running tasks, document work, and agent execution stay visible, controllable, and reviewable.',
      downloadMenuTitle: 'Choose a desktop version',
      currentDeviceBadge: 'Current device',
      plannedBadge: 'Planned',
      primaryCta: 'Read docs',
      downloadUnavailableTitle: 'No Desktop installer for this environment yet',
      downloadUnavailableBody: 'You can still read the docs or browse the source to understand ZenMind Desktop, core services, and local sandboxing.',
      featuresEyebrow: 'Core features',
      featuresTitle: 'Core capabilities at a glance',
      featuresIntro: 'A scan-friendly view of Desktop, Agent UI, models, sandboxes, and market capabilities.',
      capabilityCards: [
        {
          key: 'desktop',
          title: 'Desktop',
          body: 'Install, start, monitor, and configure from one place.',
        },
        {
          key: 'agent',
          title: 'Agent UI',
          body: 'Streaming output, human confirmation, and recoverable tasks.',
        },
        {
          key: 'models',
          title: 'Models',
          body: 'Model providers, capability flags, and usage tracking.',
        },
        {
          key: 'sandbox',
          title: 'Sandbox',
          body: 'Long-running tasks and tool execution environments.',
        },
        {
          key: 'market',
          title: 'Market',
          body: 'Skills, plugins, and workflow template entries.',
        },
      ],
      workflow: {
        eyebrow: 'ZenMind Workflow',
        title: 'Connect desktop, models, and sandboxes\ninto one workflow',
        intro: 'Less concept, more task flow: see how a task starts, runs, and stays controllable.',
        panelTitle: 'Start from desktop, keep tasks running',
        panelIntro: 'Service startup, model access, sandbox execution, and human confirmation live in one desktop entry.',
        tags: ['Service startup', 'Sandbox execution', 'Human confirmation'],
        steps: [
          { status: 'Ready', title: 'Desktop control center', body: 'Manage local services in one place' },
          { status: 'Live', title: 'Agent execution view', body: 'Visible process, easy takeover' },
          { status: 'Run', title: 'Models and sandboxes', body: 'Connect models and tool environments' },
        ],
      },
      showcases: [
        {
          key: 'desktop',
          title: 'Desktop manages the runtime',
          body: 'Put services, logs, and settings in one controllable entry.',
          mediaType: 'image',
        },
        {
          key: 'agent',
          title: 'Agent execution stays visible',
          body: 'Streaming output, human confirmation, and task recovery make long-running work clearer.',
          mediaType: 'video',
        },
      ],
      finalCtaTitle: 'Try ZenMind now',
      finalCtaBody: 'Desktop-first AI Agent platform for local, web, and mobile workflows.',
      footerTagline: 'Desktop-first AI Agent platform for local, web, and mobile workflows.',
    },
    documents: {
      eyebrow: 'Documents',
      title: 'Documents',
      intro:
        'A combined software and developer documentation entry: start with download, login, and product usage, then continue into architecture, protocols, models, sandboxes, and market capabilities.',
      sectionLabel: 'Doc sections',
      audienceLabel: 'For',
      actionLabel: 'View docs',
      docSections: [
        {
          title: 'Get started',
          intro: 'For first-time ZenMind users: download, login, profile, and public FAQ.',
          cards: [
            {
              title: 'Download and install',
              body: 'Choose the desktop installer for your platform and review the current macOS, Windows, and Linux status.',
              audience: 'New users',
              status: 'ready',
              href: '/en/download',
            },
            {
              title: 'Login and profile',
              body: 'Sign in with an email code or Google, then open your profile from the account menu in a new tab.',
              audience: 'Account users',
              status: 'preview',
              href: '/en/profile',
            },
            {
              title: 'FAQ and privacy',
              body: 'Review public questions, data boundaries, and privacy notes before rollout.',
              audience: 'All users',
              status: 'ready',
              href: '/en/faq',
            },
          ],
        },
        {
          title: 'Product capabilities',
          intro: 'Understand ZenMind Desktop, model support, and cross-client direction.',
          cards: [
            {
              title: 'Desktop workspace',
              body: 'Desktop shell manages local services, agent runtime, logs, and health status from one place.',
              audience: 'Desktop users',
              status: 'preview',
              href: externalLinks.architecture,
            },
            {
              title: 'Model support',
              body: 'Read about provider registry, model capabilities, usage mapping, and model ecosystem priorities.',
              audience: 'Model users',
              status: 'preview',
              href: externalLinks.models,
            },
            {
              title: 'Mobile direction',
              body: 'Mobile will reuse AGW UI and share the same agent experience with Desktop and Web.',
              audience: 'Cross-client users',
              status: 'soon',
              href: externalLinks.mobile,
            },
          ],
        },
        {
          title: 'Develop and integrate',
          intro: 'For developers and administrators: protocols, sandboxes, skills, plugins, and future market capabilities.',
          cards: [
            {
              title: 'Architecture',
              body: 'Review responsibilities across Desktop, App Server, Agent Platform, Web Client, and Container Hub.',
              audience: 'Developers',
              status: 'ready',
              href: externalLinks.architecture,
            },
            {
              title: 'AGW UI Protocol',
              body: 'Event model, streaming transport, HITL states, and viewport contract between clients and Agent Platform.',
              audience: 'Protocol developers',
              status: 'preview',
              href: externalLinks.agwui,
            },
            {
              title: 'Market capabilities',
              body: 'Review how skills, sandboxes, plugins, model providers, and workflow templates are presented publicly.',
              audience: 'Extension developers',
              status: 'preview',
              href: marketLinks.en,
              external: true,
            },
          ],
        },
      ],
    },
    download: {
      title: 'Download center',
      intro: 'Choose your platform to install ZenMind Desktop.',
      recommendation: {
        eyebrow: 'Recommended',
        titlePrefix: 'Recommended for',
        unavailableTitle: 'No installer is available for this platform yet',
        unavailableBody: 'You can still read the docs or browse the source to understand how ZenMind Desktop runs.',
        unknownLabel: 'Current system',
      },
      platformsTitle: 'Choose a platform',
      recommendedBadge: 'Recommended',
      loadingBadge: 'Loading',
      loadingBody: 'Reading the current installer versions. Please wait.',
      maintenanceBadge: 'Maintenance',
      maintenanceBody: 'Installer version service is temporarily unavailable. Please try again later.',
      downloadedCountPrefix: 'Downloaded ',
      downloadedCountSuffix: ' times',
      detailsLabel: 'Install notes',
      docsCta: 'Read docs',
      sourceCta: 'View source',
      desktop: {
        eyebrow: 'Desktop',
        title: 'Download ZenMind Desktop',
        intro: 'Install the desktop app to manage local services, agent runtime, logs, and health from one place.',
        visualTitle: 'ZenMind Desktop',
        visualRows: ['Service center', 'Agent runtime', 'Local sandbox', 'Cross-client entry'],
      },
      mobile: {
        eyebrow: 'Mobile',
        title: 'Download ZenMind Mobile',
        intro: 'Mobile is planned and will continue to reuse AGW UI and the Desktop-first workflow.',
        status: 'Coming soon',
        visualTitle: 'ZenMind Mobile',
        visualRows: ['Chat continuity', 'Task status', 'Mobile workflow'],
      },
    },
    news: {
      eyebrow: 'News',
      title: 'News',
      intro:
        'Product updates and AI industry observations in one place. Product updates follow the ZenMind roadmap; industry observations link to official sources instead of live news scraping.',
      productTitle: 'Product updates',
      productIntro: 'Public progress around the website, desktop app, account entry, and capability market.',
      industryTitle: 'AI industry observations',
      industryIntro: 'Trends around model capability, agent workflows, local runtime, and enterprise AI tooling.',
      sourceLabel: 'Official source',
      productUpdates: [
        {
          phase: 'Website',
          title: 'Navigation reorganized around docs, news, market, and download',
          body: 'Public entry points now separate download, login, profile, and administrator access more clearly.',
          status: 'ready',
        },
        {
          phase: 'Account',
          title: 'Profile becomes the signed-in user entry',
          body: 'Users remain on the public website after login and open profile in a new tab from the account menu.',
          status: 'preview',
        },
        {
          phase: 'Market',
          title: 'Capability market organized by skills, sandboxes, and plugins',
          body: 'The market starts as a static showcase and can later host skills, sandbox templates, plugins, and workflow templates.',
          status: 'preview',
        },
      ],
      industryTrends: [
        {
          phase: 'Models',
          title: 'Frontier models continue moving toward reasoning, multimodality, and tool use',
          body: 'Model providers keep making reasoning ability, long context, multimodal input, and tool use core product directions.',
          href: externalLinks.openAiNews,
          source: 'OpenAI News',
        },
        {
          phase: 'Agents',
          title: 'Agent products increasingly emphasize controllable workflows and human confirmation',
          body: 'The important shift is from one-off chat to recoverable, confirmable, and observable task flows.',
          href: externalLinks.anthropicNews,
          source: 'Anthropic News',
        },
        {
          phase: 'Multimodal',
          title: 'AI entry points expand beyond chat into search, devices, and work tools',
          body: 'AI capabilities are being embedded into search, browsers, office tools, mobile devices, and developer tools.',
          href: externalLinks.googleAiBlog,
          source: 'Google AI Blog',
        },
        {
          phase: 'Local runtime',
          title: 'Local compute and personal AI devices make desktop runtime important again',
          body: 'Desktop and local runtimes support privacy, low latency, tool execution, and local file workflows.',
          href: externalLinks.nvidiaAiNews,
          source: 'NVIDIA News',
        },
      ],
    },
    login: {
      eyebrow: 'Login',
      title: 'Login to ZenMind',
      intro: 'Continue through ZenMind unified authentication.',
      portalTitle: 'Login to ZenMind',
      portalBody: 'Continue through ZenMind unified authentication.',
      highlights: ['Unified SSO', 'Google and email code', 'Secure session'],
      formTitle: 'Email code sign-in',
      emailLabel: 'Email',
      codeLabel: '6-digit code',
      codePlaceholder: 'Enter code',
      sendCode: 'Send code',
      resendCode: 'Send again',
      codeSent: 'Code sent. Check your inbox.',
      verifySubmit: 'Sign in / Register',
      separator: 'or',
      passwordLabel: 'Password',
      adminLoginTitle: 'Admin password login',
      adminLoginSummary: 'Existing administrator accounts can still use password login.',
      submit: 'Admin login',
      googleSubmit: 'Continue with Google',
      ssoSubmit: 'Continue with unified SSO',
      submitting: 'Working',
      sendingCode: 'Sending',
      verifyingCode: 'Verifying',
      checking: 'Checking session',
      signedIn: 'Signed in',
      signedOut: 'Signed out',
      welcome: 'Current account',
      profileCta: 'Open profile',
      homeCta: 'Back home',
      accountLabel: 'Account',
      roleLabel: 'Role',
      providerLabel: 'Method',
      logout: 'Log out',
      sessionTitle: 'Secure sign-in',
      sessionBody: 'ZenMind provides first-party authentication. Credentials remain in a secure HttpOnly session cookie.',
      errorFallback: 'Request failed. Please try again.',
    },
    profile: {
      eyebrow: 'Profile',
      title: 'Profile',
      intro: 'View your account status, ZenMind usage overview, and model API consumption.',
      accountTitle: 'Account overview',
      usageTitle: 'Model API usage',
      trendsTitle: 'Last 7 days',
      providersTitle: 'Provider distribution',
      settingsTitle: 'Account settings',
      settingsBody: 'Profile, login method, and security editing will open in a later version.',
      loginPromptTitle: 'Sign in required',
      loginPromptBody: 'Sign in to view your profile, account status, and usage overview.',
      signInCta: 'Go to login',
      fields: {
        email: 'Email',
        role: 'Role',
        provider: 'Login method',
        status: 'Status',
      },
      metrics: {
        calls: 'Monthly calls',
        tokens: 'Monthly tokens',
        cost: 'Estimated cost',
        recentModel: 'Recent model',
      },
      emptyMetric: 'Preparing',
    },
    adminLogin: {
      eyebrow: 'Admin',
      title: 'Admin login',
      intro: 'Enter administrator account details to continue.',
      portalTitle: 'Administrator entry',
      portalBody: 'Use this entry to review site-wide usage, downloads, and administrator overview. Administrator access must be enforced by the server.',
      highlights: ['Site-wide model API usage', 'Users and downloads', 'Server-side permission checks'],
      emailLabel: 'Admin email',
      passwordLabel: 'Admin password',
      submit: 'Enter admin',
      submitting: 'Signing in',
      securityNote: 'Administrator access is verified by the server.',
      errorFallback: 'Admin login failed. Please try again later.',
    },
    admin: {
      eyebrow: 'Admin',
      title: 'Admin',
      intro: 'View site-wide usage, downloads, and administrator overview.',
      loginRequiredTitle: 'Admin login required',
      loginRequiredBody: 'Please sign in through the administrator entry first.',
      loginCta: 'Go to admin login',
      noPermissionTitle: 'This account does not have administrator access',
      noPermissionBody: 'Use an administrator account before opening this page.',
      overviewTitle: 'Site overview',
      trendsTitle: 'Site usage trend',
      metrics: {
        calls: 'Site calls',
        tokens: 'Site tokens',
        cost: 'Estimated cost',
        users: 'Active users',
        downloads: 'Downloads',
        providers: 'Provider distribution',
      },
      activityTitle: 'Recent activity',
    },
    authFailure: {
      eyebrow: 'OAuth Failure',
      title: 'Google sign-in did not finish',
      intro: 'Google authorization did not create a ZenMind session this time. You can try signing in again or return home.',
      status: 'Sign-in failed',
      reasonLabel: 'Error code',
      unknownReason: 'unknown',
      reasonHelp: 'If the same error code keeps appearing, ask an administrator to check Google OAuth settings and server logs.',
      loginCta: 'Back to login',
      homeCta: 'Back home',
    },
    footer: {
      rights: 'All rights reserved.',
      source: 'Source repo',
      status: 'Static public website',
      note: 'The website hosts public pages, download entry points, and product notes.',
      siteLinks: 'Site',
      resources: 'Resources',
    },
  };
