import { externalLinks, marketLinks } from './links';
import { siteUrl } from './site';

export const zh = {
    code: 'zh-CN',
    switchLabel: 'EN',
    brandMark: 'ZenMind',
    seo: {
      title: 'ZenMind | Desktop-first AI Agent 平台',
      description:
        'ZenMind 是以 Desktop 为入口的 AI Agent 平台，连接本地服务、Web/移动端工作流、国产模型生态与本地沙箱。',
      url: siteUrl,
    },
    nav: {
      home: '首页',
      download: '下载',
      documents: '文档',
      news: '新闻',
      market: '市场',
      login: '登录',
      adminLogin: '管理员登录',
      profile: '个人主页',
      admin: '管理后台',
      authFailure: '登录失败',
      github: 'GitHub',
    },
    theme: {
      label: '主题',
      auto: '自动',
      light: '白天',
      dark: '黑夜',
    },
    shared: {
      copyLabel: '复制',
      copiedLabel: '已复制',
      openGithub: 'GitHub',
      readDocs: '阅读文档',
      deployDocs: '部署入口',
      downloadDesktop: '下载桌面端',
      openProfile: '个人主页',
      logout: '退出登录',
      currentAccount: '当前账号',
      notSignedIn: '未登录',
      noPermission: '无权限',
      usagePreparing: '用量数据准备中',
      statusReady: '可用',
      statusSoon: '规划中',
      statusPreview: '预览',
      externalLabel: '打开外链',
      downloadFallback: '查看文档',
      downloadTotalPrefix: '总下载 ',
      downloadTotalSuffix: ' 次',
    },
    home: {
      eyebrow: 'Desktop-first AI Agent Platform',
      headline: '让智能体在你的桌面持续工作',
      heroIntro:
        'ZenMind 将桌面端、本地服务、模型连接与沙箱环境组织成一个可控工作台，让长期任务、文档处理和 Agent 执行过程可见、可控、可复盘。',
      downloadMenuTitle: '选择版本下载桌面端',
      currentDeviceBadge: '当前设备',
      plannedBadge: '规划中',
      primaryCta: '查看文档',
      downloadUnavailableTitle: '当前环境暂未提供 Desktop 安装包',
      downloadUnavailableBody: '你仍然可以查看文档或源码，了解 ZenMind Desktop、核心服务和本地沙箱的运行方式。',
      featuresEyebrow: '核心功能',
      featuresTitle: '核心能力一眼看懂',
      featuresIntro: '把原来偏长的功能叙事压缩成更易扫描的能力入口：Desktop、Agent UI、模型、沙箱和市场。',
      capabilityCards: [
        {
          key: 'desktop',
          title: 'Desktop',
          body: '统一安装、启动、监控和设置。',
        },
        {
          key: 'agent',
          title: 'Agent UI',
          body: '流式输出、人工确认和可恢复任务。',
        },
        {
          key: 'models',
          title: 'Models',
          body: '模型 Provider、能力标记和用量统计。',
        },
        {
          key: 'sandbox',
          title: 'Sandbox',
          body: '长期任务和工具执行环境。',
        },
        {
          key: 'market',
          title: 'Market',
          body: '技能、插件和工作流模板入口。',
        },
      ],
      workflow: {
        eyebrow: 'ZenMind Workflow',
        title: '把桌面、模型和沙箱\n连成一个工作流',
        intro: '少讲概念，先看一条任务如何启动、执行和接管。',
        panelTitle: '从桌面启动，到任务持续执行',
        panelIntro: '服务启动、模型接入、沙箱执行和人工确认被放进同一个桌面入口。',
        tags: ['服务启动', '沙箱执行', '人工确认'],
        steps: [
          { status: 'Ready', title: 'Desktop 控制中心', body: '统一管理本地服务' },
          { status: 'Live', title: 'Agent 执行视图', body: '过程可见，随时接管' },
          { status: 'Run', title: '模型与沙箱环境', body: '连接模型与工具环境' },
        ],
      },
      showcases: [
        {
          key: 'desktop',
          title: 'Desktop 管理运行时',
          body: '把服务、日志和设置放在一个可控入口里。',
          mediaType: 'image',
        },
        {
          key: 'agent',
          title: 'Agent 过程可见可控',
          body: '流式输出、人工确认和任务续接，让长期任务更透明。',
          mediaType: 'video',
        },
      ],
      finalCtaTitle: '立即试用 ZenMind',
      finalCtaBody: '面向桌面、本地服务与多端工作流的 AI Agent 平台。',
      footerTagline: '面向桌面、本地服务与多端工作流的 AI Agent 平台。',
    },
    documents: {
      eyebrow: 'Documents',
      title: '文档',
      intro: '软件使用与开发说明的统一入口：先帮助用户完成下载、登录和使用，再承接架构、协议、模型、沙箱和能力市场说明。',
      sectionLabel: '文档分组',
      audienceLabel: '适合',
      actionLabel: '查看文档',
      docSections: [
        {
          title: '快速上手',
          intro: '面向第一次进入 ZenMind 的用户，覆盖下载、登录、个人主页与常见问题。',
          cards: [
            {
              title: '下载安装',
              body: '按平台选择桌面端安装包，了解 macOS、Windows 与 Linux 的当前可用状态。',
              audience: '新用户',
              status: 'ready',
              href: '/download',
            },
            {
              title: '登录与个人主页',
              body: '使用邮箱验证码或 Google 登录，登录后从头部账号菜单打开个人主页。',
              audience: '账号用户',
              status: 'preview',
              href: '/profile',
            },
            {
              title: 'FAQ 与隐私',
              body: '查看官网公开问题、数据边界和隐私说明，适合作为上线前的基础说明入口。',
              audience: '所有用户',
              status: 'ready',
              href: '/faq',
            },
          ],
        },
        {
          title: '产品能力',
          intro: '说明 ZenMind Desktop、模型生态和跨端方向，帮助用户理解产品边界。',
          cards: [
            {
              title: 'Desktop 工作台',
              body: 'Desktop shell 统一管理本地服务、Agent 运行时、日志和健康状态。',
              audience: '桌面端用户',
              status: 'preview',
              href: externalLinks.architecture,
            },
            {
              title: '模型支持',
              body: '了解 provider registry、模型能力、用量映射和模型生态优先级。',
              audience: '模型使用者',
              status: 'preview',
              href: externalLinks.models,
            },
            {
              title: '移动端方向',
              body: '移动端将复用 AGW UI 协议，与 Desktop/Web 共享同一套 Agent 体验。',
              audience: '跨端用户',
              status: 'soon',
              href: externalLinks.mobile,
            },
          ],
        },
        {
          title: '开发与集成',
          intro: '面向开发者和管理员，解释协议、沙箱、技能、插件以及未来市场能力。',
          cards: [
            {
              title: '架构说明',
              body: '查看 Desktop、App Server、Agent Platform、Web Client 与 Container Hub 的职责边界。',
              audience: '开发者',
              status: 'ready',
              href: externalLinks.architecture,
            },
            {
              title: 'AGW UI 协议',
              body: '客户端与 Agent Platform 之间的事件模型、流式传输、HITL 与 viewport 契约。',
              audience: '协议开发者',
              status: 'preview',
              href: externalLinks.agwui,
            },
            {
              title: '能力市场说明',
              body: '查看技能、沙箱、插件、模型 Provider 和工作流模板的公开展示方式。',
              audience: '扩展开发者',
              status: 'preview',
              href: marketLinks.zh,
              external: true,
            },
          ],
        },
      ],
    },
    download: {
      title: '下载中心',
      intro: '选择你的平台下载安装 ZenMind Desktop',
      recommendation: {
        eyebrow: '推荐下载',
        titlePrefix: '推荐下载',
        unavailableTitle: '当前平台暂未开放安装包',
        unavailableBody: '你仍然可以查看文档或源码，了解 ZenMind Desktop 的安装与运行方式。',
        unknownLabel: '当前系统',
      },
      platformsTitle: '选择平台',
      recommendedBadge: '推荐',
      loadingBadge: '加载中',
      loadingBody: '正在读取当前安装包版本，请稍候。',
      maintenanceBadge: '维护中',
      maintenanceBody: '安装包版本服务暂时不可用，请稍后再试。',
      downloadedCountPrefix: '已下载 ',
      downloadedCountSuffix: ' 次',
      detailsLabel: '安装说明',
      docsCta: '查看文档',
      sourceCta: '查看源码',
      desktop: {
        eyebrow: 'Desktop',
        title: '下载 ZenMind 桌面版',
        intro: '安装桌面版后统一管理本地服务、Agent 运行时、日志与健康状态。',
        visualTitle: 'ZenMind Desktop',
        visualRows: ['服务中心', 'Agent 运行时', '本地沙箱', '跨端入口'],
      },
      mobile: {
        eyebrow: 'Mobile',
        title: '下载 ZenMind 移动版',
        intro: '移动端正在规划中，将继续复用 AGW UI 协议与 Desktop-first 工作流。',
        status: '敬请期待',
        visualTitle: 'ZenMind Mobile',
        visualRows: ['对话续接', '任务状态', '移动工作流'],
      },
    },
    news: {
      eyebrow: 'News',
      title: '新闻',
      intro: '这里同时展示 ZenMind 产品动态和 AI 行业观察。产品动态来自官网路线，行业观察链接到官方来源，不做实时新闻抓取。',
      productTitle: '产品动态',
      productIntro: '围绕官网、桌面端、账号入口和能力市场的公开进展。',
      industryTitle: 'AI 行业观察',
      industryIntro: '关注模型能力、Agent 工作流、本地运行和企业 AI 工具化趋势。',
      sourceLabel: '官方来源',
      productUpdates: [
        {
          phase: '官网',
          title: '官网入口重组为文档、新闻、市场、下载',
          body: '顶部导航围绕公开门户重新排序，下载、登录、个人主页和管理员入口的职责更加清晰。',
          status: 'ready',
        },
        {
          phase: '账号',
          title: '个人主页成为登录后的用户入口',
          body: '普通用户登录后仍停留在官网，点击个人主页后在新标签页查看账号状态和模型 API 用量占位。',
          status: 'preview',
        },
        {
          phase: '市场',
          title: '功能市场按技能、沙箱、插件组织',
          body: '市场页先做静态展示，后续可逐步承接技能包、沙箱模板、插件和工作流模板。',
          status: 'preview',
        },
      ],
      industryTrends: [
        {
          phase: '模型',
          title: '前沿模型继续向推理、多模态和工具调用演进',
          body: '模型厂商持续把推理能力、长上下文、多模态输入和工具调用作为核心产品方向。',
          href: externalLinks.openAiNews,
          source: 'OpenAI News',
        },
        {
          phase: 'Agent',
          title: 'Agent 产品开始强调可控流程和人工确认',
          body: '从单次对话走向可恢复、可确认、可观测的任务流，是企业和开发者工具的重要趋势。',
          href: externalLinks.anthropicNews,
          source: 'Anthropic News',
        },
        {
          phase: '多模态',
          title: 'AI 入口从文本对话扩展到搜索、设备和工作流',
          body: 'AI 能力正在嵌入搜索、浏览器、办公、移动设备和开发工具，入口形态更加分散。',
          href: externalLinks.googleAiBlog,
          source: 'Google AI Blog',
        },
        {
          phase: '本地运行',
          title: '本地算力和个人 AI 设备推动桌面端重新变重要',
          body: '桌面端和本地运行时能承接隐私、低延迟、工具执行和本地文件场景。',
          href: externalLinks.nvidiaAiNews,
          source: 'NVIDIA News',
        },
      ],
    },
    login: {
      eyebrow: 'Login',
      title: '登录 ZenMind',
      intro: '通过 ZenMind 统一认证继续。',
      portalTitle: '登录 ZenMind',
      portalBody: '通过 ZenMind 统一认证继续。',
      highlights: ['统一 SSO', 'Google 与邮箱验证码', '安全会话'],
      formTitle: '邮箱验证码登录',
      emailLabel: '邮箱',
      codeLabel: '6 位验证码',
      codePlaceholder: '请输入验证码',
      sendCode: '发送验证码',
      resendCode: '重新发送',
      codeSent: '验证码已发送，请查看邮箱。',
      verifySubmit: '登录 / 注册',
      separator: '或',
      passwordLabel: '密码',
      adminLoginTitle: '管理员密码登录',
      adminLoginSummary: '已有管理员账号可继续使用密码登录。',
      submit: '管理员登录',
      googleSubmit: '使用 Google 登录',
      ssoSubmit: '使用统一认证登录',
      submitting: '处理中',
      sendingCode: '发送中',
      verifyingCode: '验证中',
      checking: '检查会话',
      signedIn: '已登录',
      signedOut: '未登录',
      welcome: '当前账号',
      profileCta: '打开个人主页',
      homeCta: '返回首页',
      accountLabel: '账号',
      roleLabel: '角色',
      providerLabel: '登录方式',
      logout: '退出登录',
      sessionTitle: '安全登录',
      sessionBody: 'ZenMind 直接提供统一认证。登录凭据只保存在安全的 HttpOnly 会话 Cookie 中。',
      errorFallback: '请求失败，请稍后重试。',
    },
    profile: {
      eyebrow: 'Profile',
      title: '个人主页',
      intro: '查看你的账号状态、ZenMind 使用概览和模型 API 消耗。',
      accountTitle: '账号概览',
      usageTitle: '模型 API 用量',
      trendsTitle: '近 7 天趋势',
      providersTitle: 'Provider 分布',
      settingsTitle: '账号设置',
      settingsBody: '个人资料、登录方式和安全设置会在后续版本开放编辑。',
      loginPromptTitle: '请先登录',
      loginPromptBody: '登录后可以查看个人主页、账号状态和用量概览。',
      signInCta: '前往登录',
      fields: {
        email: '邮箱',
        role: '角色',
        provider: '登录方式',
        status: '状态',
      },
      metrics: {
        calls: '本月调用',
        tokens: '本月 token',
        cost: '费用估算',
        recentModel: '最近模型',
      },
      emptyMetric: '准备中',
    },
    adminLogin: {
      eyebrow: 'Admin',
      title: '管理员登录',
      intro: '请输入管理员账号信息继续。',
      portalTitle: '管理员入口',
      portalBody: '用于查看全站用量、下载统计和管理员概览。管理员权限必须由服务端校验。',
      highlights: ['全站模型 API 用量', '用户与下载统计', '服务端权限校验'],
      emailLabel: '管理员邮箱',
      passwordLabel: '管理员密码',
      submit: '进入管理后台',
      submitting: '登录中',
      securityNote: '管理员权限由服务端校验。',
      errorFallback: '管理员登录失败，请稍后重试。',
    },
    admin: {
      eyebrow: 'Admin',
      title: '管理后台',
      intro: '查看全站用量、下载统计和管理员概览。',
      loginRequiredTitle: '需要管理员登录',
      loginRequiredBody: '请先通过管理员入口登录。',
      loginCta: '前往管理员登录',
      noPermissionTitle: '当前账号没有管理员权限',
      noPermissionBody: '请使用管理员账号登录后再访问该页面。',
      overviewTitle: '全站概览',
      trendsTitle: '全站用量趋势',
      metrics: {
        calls: '全站调用',
        tokens: '全站 token',
        cost: '费用估算',
        users: '活跃用户',
        downloads: '下载统计',
        providers: 'Provider 分布',
      },
      activityTitle: '最近活动',
    },
    authFailure: {
      eyebrow: 'OAuth Failure',
      title: 'Google 登录未完成',
      intro: '这次 Google 授权没有成功建立 ZenMind 会话。你可以重新登录，或先返回首页。',
      status: '登录失败',
      reasonLabel: '错误码',
      unknownReason: 'unknown',
      reasonHelp: '如果连续出现同一个错误码，请联系管理员检查 Google OAuth 配置和服务端日志。',
      loginCta: '返回登录',
      homeCta: '返回首页',
    },
    footer: {
      rights: 'All rights reserved.',
      source: '主仓库',
      status: 'Static public website',
      note: '官网只承载公开页面、下载入口和说明。',
      siteLinks: '站点入口',
      resources: '资源',
    },
  };
